### ISSUE TITLE
pyupgrade

### ISSUE THREAD

**Issue by VeckoTheGecko** [SECOORA/GUTILS#30]
**Suggestions**

- [ ] Wait on #22 (to avoid merge conflicts)
- [x] ~~Add [pre-commit.ci](https://pre-commit.ci/) to repo~~ Pre-commit is already in the `push.yml` GHA workflow
  - **Pros:** Pre commit hooks run in CI for pull requests (independent of dev install). No associated cost for public repos.
- [ ] Modify `.pre-commit-config.yaml` to add pyupgrade
  - **Pros:** Automatically remove outdated Python syntax, and convert code to take advantage of new features (e.g., f-strings, remove encoding comments)
  - **Cons:** Requires explicitly dropping support for Python versions as per arg in pyupgrade workflow

**Addition to `.pre-commit-config.yaml`**

```yml
- repo: https://github.com/asottile/pyupgrade
  rev: v3.15.0
  hooks:
    - id: pyupgrade
      args: [--py36-plus]
```
